//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncodageEmploi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emploi()
        {
            this.Risque = new HashSet<Risque>();
        }
    
        public int idTravail { get; set; }
        public int travailleur { get; set; }
        public int entreprise { get; set; }
        public decimal codeTravail { get; set; }
        public System.DateTime dateEntree { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public int denom { get; set; }
    
        public virtual DenominationEmploi DenominationEmploi { get; set; }
        public virtual Entreprise Entreprise1 { get; set; }
        public virtual Travailleur Travailleur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Risque> Risque { get; set; }
    }
}
