//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncodageEmploi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entreprise()
        {
            this.Emploi = new HashSet<Emploi>();
        }
    
        public int numero { get; set; }
        public string denominationEntreprise { get; set; }
        public string numTel { get; set; }
        public decimal nbrTravSoumis { get; set; }
        public decimal nbrTravNonSoumis { get; set; }
        public int idLangue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emploi> Emploi { get; set; }
        public virtual Langue Langue { get; set; }
    }
}
