//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncodageEmploi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIG3A5Entities : DbContext
    {
        public DBIG3A5Entities()
            : base("name=DBIG3A5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DenominationEmploi> DenominationEmploi { get; set; }
        public virtual DbSet<DenominationRisque> DenominationRisque { get; set; }
        public virtual DbSet<Emploi> Emploi { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Langue> Langue { get; set; }
        public virtual DbSet<Risque> Risque { get; set; }
        public virtual DbSet<Travailleur> Travailleur { get; set; }
    }
}
